[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; On force PlatformIO à bien scanner toutes les dépendances
lib_ldf_mode = deep+

lib_deps =
    ; On lie la librairie locale Common proprement
    symlink://../Common

    ; Dépendances nécessaires pour le projet et la lib Common
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.0
    tzapu/WiFiManager@^2.0.17
    arduino-libraries/NTPClient@^3.2.1
    
    ; Librairies spécifiques au BMP280
    adafruit/Adafruit BMP280 Library@^2.6.8
    adafruit/Adafruit Unified Sensor@^1.1.15
    adafruit/Adafruit BusIO@^1.17.4
    
    WiFiClientSecure
